### ISSUE TITLE
Bug in filter-appearance in tutorial 3

### ISSUE THREAD

**Issue by pdmct** [xtdb/xtdb-tutorial#18]
There is an insidious typo in the example code for `filter-appearance`.

Currently:
```
(defn filter-appearance
  [description]
  (xt/q (xt/db node)
        '{:find [name IUPAC]
          :where [[e :common-name name]
                  [e :IUPAC-name IUPAC]
                  [e :appearance appearance]]
          :in [apperance]}
        description))
```
the `:in` parameter is misspelled.

The usage example `(filter-appearance "white solid")` always returns the correct result since there is only one item with an `:appearance` attribute.

**Comment by deobald** [comment]
Ha! Nice catch, @pdmct . Fixed in https://github.com/xtdb/xtdb-tutorial/commit/3c4a202e11c65a0aac21b84eaae907b6ce8f0c79 and will go out with the next release.
